/**
 * Auto-generated by make_message.py on 02/27/2023 (01:17:44)
 * Don't edit this unless you know what you are doing,
 * as manual changes will be overwritten on the next build.
 */

#ifndef BCMSG_RICHPRESENCE_H
#define BCMSG_RICHPRESENCE_H

namespace caddie {

enum BCMSG_RichPresence {
    MSG_RPC_STATE_MENU,
    MSG_RPC_STATE_SWF_VS,
    MSG_RPC_STATE_SWF_PRC,
    MSG_RPC_STATE_SWF_SGL,
    MSG_RPC_STATE_WKB,
    MSG_RPC_STATE_FLD,
    MSG_RPC_STATE_DGL,
    MSG_RPC_STATE_ARC,
    MSG_RPC_STATE_BSK_3PT,
    MSG_RPC_STATE_BSK_VS,
    MSG_RPC_STATE_PNG,
    MSG_RPC_STATE_PNG_RET,
    MSG_RPC_STATE_GLF,
    MSG_RPC_STATE_BWL_STD,
    MSG_RPC_STATE_BWL_100,
    MSG_RPC_STATE_BWL_WAL,
    MSG_RPC_STATE_JSK_RNG,
    MSG_RPC_STATE_JSK_VS,
    MSG_RPC_STATE_CAN,
    MSG_RPC_STATE_CAN_VS,
    MSG_RPC_STATE_BIC,
    MSG_RPC_STATE_BIC_VS,
    MSG_RPC_STATE_OMK,
    MSG_RPC_STATE_PLN,
    MSG_RPC_STATE_PLN_VS,
};

} // namespace caddie

#endif
