/**
 * Auto-generated by caddie_message.py on 02/22/2023 (10:58:39)
 * Don't edit this unless you know what you are doing,
 * as manual changes will be overwritten on the next build.
 */

#ifndef CMSG_TESTMESSAGE_H
#define CMSG_TESTMESSAGE_H

namespace caddie {

enum TestMessage {
    MSG_CMN_TEST,
    MSG_CMN_TEST_TWO,
    MSG_CMN_TEST_THREE,
    MSG_CMN_TEST_FOUR,
};

} // namespace caddie

#endif
